/**
 * The macOS launcher bundle the launchd agent points at.
 *
 * Why this exists: macOS Background Task Management (System Settings → General
 * → Login Items & Extensions, and the "… can run in the background"
 * notification) names a launchd agent after the *program the job launches*, not
 * after the job's `Label`. Pointing `ProgramArguments[0]` straight at the Node
 * binary therefore surfaced the daemon to users as an anonymous **"node"** —
 * indistinguishable from any other Node-based background item on the machine,
 * and easy to disable by mistake.
 *
 * So `ac2 service install` writes a tiny `AC2.app` under the AC2 home whose
 * only executable is a shell launcher that `exec`s the real command. Because
 * the job's program now lives inside a bundle, macOS reads the bundle's
 * `CFBundleName` and shows **"AC2"**; even if it ever falls back to the plain
 * executable name it reads `ac2d`, never `node`.
 *
 * The bundle is generated (never shipped), lives next to the rest of the
 * daemon's state, is rewritten on every install, and is removed by
 * `ac2 service uninstall`.
 */

import { chmod, mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/** Directory name of the generated launcher bundle, and the visible name. */
export const DARWIN_APP_BUNDLE_NAME = 'AC2.app';

/** `CFBundleExecutable`: the fallback name macOS shows if it ignores the bundle. */
export const DARWIN_APP_EXECUTABLE_NAME = 'ac2d';

/** Bundle identifier, matching the launchd label. */
export const DARWIN_APP_BUNDLE_ID = 'com.algorandfoundation.ac2';

/** Human-readable name macOS displays for the background item. */
export const DARWIN_APP_DISPLAY_NAME = 'AC2';

/** Quotes one argument for a `/bin/sh` command line. */
function shellQuote(arg: string): string {
  return `'${arg.replace(/'/g, `'\\''`)}'`;
}

/**
 * Renders the bundle's `Contents/Info.plist`.
 *
 * `LSBackgroundOnly`/`LSUIElement` keep the launcher out of the Dock and the
 * app switcher — it is a daemon, not something the user ever brings to front.
 */
export function renderDarwinAppInfoPlist(opts: { version?: string } = {}): string {
  const version = opts.version ?? '1.0';
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>${DARWIN_APP_EXECUTABLE_NAME}</string>
  <key>CFBundleIdentifier</key>
  <string>${DARWIN_APP_BUNDLE_ID}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${DARWIN_APP_DISPLAY_NAME}</string>
  <key>CFBundleDisplayName</key>
  <string>${DARWIN_APP_DISPLAY_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>${version}</string>
  <key>CFBundleVersion</key>
  <string>${version}</string>
  <key>LSBackgroundOnly</key>
  <true/>
  <key>LSUIElement</key>
  <true/>
</dict>
</plist>
`;
}

/**
 * Renders the launcher script that `exec`s the daemon command.
 *
 * `exec` matters: the launcher must not linger as a parent process, so launchd
 * supervises (and signals) the daemon itself.
 */
export function renderDarwinLauncherScript(execStart: string[]): string {
  if (execStart.length === 0) throw new Error('execStart must not be empty');
  return [
    '#!/bin/sh',
    '# Generated by `ac2 service install` — do not edit.',
    '# Exists so macOS shows this background item as "AC2" instead of "node".',
    `exec ${execStart.map(shellQuote).join(' ')} "$@"`,
    '',
  ].join('\n');
}

export interface DarwinAppBundleResult {
  /** Path of the generated `AC2.app`. */
  bundlePath: string;
  /** Path of the launcher launchd must run. */
  executablePath: string;
  /** Whether the ad-hoc code signature was applied. */
  signed: boolean;
}

export interface DarwinAppBundleOptions {
  /** Directory the bundle is created in (normally the AC2 home). */
  dir: string;
  /** The command the launcher execs, e.g. `[node, cli.js, 'service', 'run']`. */
  execStart: string[];
  version?: string;
  /**
   * Applies an ad-hoc code signature to the bundle, giving macOS a stable
   * identity to attribute the background item to. Best effort: signing is not
   * required for the name to appear, so failures are swallowed. Injectable for
   * tests; pass `null` to skip signing entirely.
   */
  sign?: ((bundlePath: string) => Promise<void>) | null;
}

/** Ad-hoc signs the bundle with the `codesign` tool, if it is available. */
async function adHocSign(bundlePath: string): Promise<void> {
  const { execFile } = await import('node:child_process');
  const { promisify } = await import('node:util');
  await promisify(execFile)('/usr/bin/codesign', [
    '--force',
    '--sign',
    '-',
    '--identifier',
    DARWIN_APP_BUNDLE_ID,
    bundlePath,
  ]);
}

/**
 * (Re)creates the launcher bundle and returns the executable launchd should run.
 */
export async function writeDarwinAppBundle(
  opts: DarwinAppBundleOptions,
): Promise<DarwinAppBundleResult> {
  const bundlePath = join(opts.dir, DARWIN_APP_BUNDLE_NAME);
  const macosDir = join(bundlePath, 'Contents', 'MacOS');
  const executablePath = join(macosDir, DARWIN_APP_EXECUTABLE_NAME);

  // A stale signature or leftover executable would make `codesign` refuse (and
  // could keep an outdated command around), so the bundle is rebuilt from
  // scratch on every install.
  await rm(bundlePath, { recursive: true, force: true });
  await mkdir(macosDir, { recursive: true });
  await writeFile(
    join(bundlePath, 'Contents', 'Info.plist'),
    renderDarwinAppInfoPlist(opts.version !== undefined ? { version: opts.version } : {}),
    'utf8',
  );
  // The launcher embeds the daemon's command line only — no secrets — but it is
  // executable, so it stays writable by its owner alone.
  await writeFile(executablePath, renderDarwinLauncherScript(opts.execStart), {
    encoding: 'utf8',
    mode: 0o700,
  });
  await chmod(executablePath, 0o700);

  let signed = false;
  const sign = opts.sign === undefined ? adHocSign : opts.sign;
  if (sign) {
    try {
      await sign(bundlePath);
      signed = true;
    } catch {
      // Unsigned is fine: macOS then names the item from the bundle's Info.plist.
    }
  }

  return { bundlePath, executablePath, signed };
}

/** Removes a previously generated launcher bundle. */
export async function removeDarwinAppBundle(dir: string): Promise<{ removed: boolean; path: string }> {
  const bundlePath = join(dir, DARWIN_APP_BUNDLE_NAME);
  try {
    await rm(bundlePath, { recursive: true, force: false });
    return { removed: true, path: bundlePath };
  } catch {
    return { removed: false, path: bundlePath };
  }
}
